# Generated by Django 5.2.8 on 2025-11-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unit name (e.g., inches)', max_length=50, unique=True)),
                ('symbol', models.CharField(help_text='Unit symbol (e.g., in, cm)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('category_type', models.CharField(choices=[('GARMENT', 'Garment'), ('FABRIC', 'Fabric'), ('ACCESSORY', 'Accessory')], help_text='Type of category', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_hsn_code', models.CharField(blank=True, default='', help_text='Default HSN/SAC code for items in this category', max_length=10, verbose_name='Default HSN Code')),
                ('is_system_wide', models.BooleanField(default=False, help_text='If True, this category is created by Super Admin and available to all tenants')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='If NULL, this is a system-wide category available to all tenants', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'item_categories',
                'ordering': ['category_type', 'display_order', 'name'],
                'unique_together': {('name', 'category_type', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='MeasurementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Internal field name (e.g., bust, waist)', max_length=100)),
                ('field_label', models.CharField(help_text='Display label (e.g., Bust, Waist)', max_length=100)),
                ('field_type', models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Text'), ('DROPDOWN', 'Dropdown')], default='NUMBER', max_length=20)),
                ('unit_options', models.CharField(blank=True, help_text='Comma-separated unit options (e.g., inches,cm)', max_length=200, null=True)),
                ('default_unit', models.CharField(blank=True, help_text='Default unit to use', max_length=50, null=True)),
                ('dropdown_options', models.TextField(blank=True, help_text='Comma-separated dropdown options', null=True)),
                ('is_required', models.BooleanField(default=False, help_text='Is this field required when taking measurements?')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed value (for NUMBER fields)', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed value (for NUMBER fields)', max_digits=10, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in measurement form')),
                ('help_text', models.CharField(blank=True, help_text='Help text to show users', max_length=200, null=True)),
                ('is_system_wide', models.BooleanField(default=False, help_text='If True, this field is available to all tenants')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this measurement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='measurement_fields', to='masters.itemcategory')),
                ('tenant', models.ForeignKey(blank=True, help_text='If NULL, this is a system-wide field', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_fields', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Measurement Field',
                'verbose_name_plural': 'Measurement Fields',
                'db_table': 'measurement_fields',
                'ordering': ['category', 'display_order', 'field_name'],
                'unique_together': {('category', 'field_name', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='TenantMeasurementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Show this field in measurement forms?')),
                ('custom_label', models.CharField(blank=True, help_text='Custom label for this tenant (overrides field_label)', max_length=100, null=True)),
                ('custom_help_text', models.CharField(blank=True, help_text='Custom help text for this tenant', max_length=200, null=True)),
                ('is_required', models.BooleanField(blank=True, default=None, help_text='Override system required setting (NULL = use default)', null=True)),
                ('display_order', models.IntegerField(blank=True, help_text='Custom display order (NULL = use default)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_configs', to='masters.measurementfield')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_configs', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Measurement Config',
                'verbose_name_plural': 'Tenant Measurement Configs',
                'db_table': 'tenant_measurement_configs',
                'unique_together': {('tenant', 'measurement_field')},
            },
        ),
    ]
