# Generated by Django 5.2.6 on 2025-12-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_custom_measurement_labels'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Blouse Stitching)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the service', null=True)),
                ('service_category', models.CharField(choices=[('STITCHING', 'Stitching'), ('ALTERATION', 'Alteration'), ('EMBROIDERY', 'Embroidery'), ('DESIGN', 'Design'), ('REPAIR', 'Repair'), ('IRONING', 'Ironing'), ('DYEING', 'Dyeing'), ('OTHER', 'Other')], default='STITCHING', help_text='Service category', max_length=50)),
                ('is_system_wide', models.BooleanField(default=False, help_text='If True, this service is created by Super Admin and available to all tenants')),
                ('default_price', models.DecimalField(decimal_places=2, help_text='Default/Standard price for this service', max_digits=10)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price (optional for price range)', max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price (optional for price range)', max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('PER_ITEM', 'Per Item'), ('PER_METER', 'Per Meter'), ('PER_HOUR', 'Per Hour'), ('PER_PIECE', 'Per Piece')], default='PER_ITEM', help_text='Pricing unit', max_length=50)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Tax/GST rate percentage (e.g., 18.00 for 18%)', max_digits=5)),
                ('hsn_code', models.CharField(blank=True, default='', help_text='HSN/SAC code for this service', max_length=10, verbose_name='HSN/SAC Code')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently offered')),
                ('estimated_days', models.PositiveIntegerField(blank=True, help_text='Typical completion time in days', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in lists')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this service', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='If NULL, this is a system-wide service available to all tenants', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
                'db_table': 'service_items',
                'ordering': ['service_category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='service_ite_tenant__625def_idx'), models.Index(fields=['tenant', 'service_category'], name='service_ite_tenant__c63f87_idx'), models.Index(fields=['is_system_wide', 'is_active'], name='service_ite_is_syst_386a6d_idx')],
                'unique_together': {('name', 'service_category', 'tenant')},
            },
        ),
    ]
