# Generated by Django 5.2.6 on 2025-12-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_serviceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='hsn_code',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='sac_code',
            field=models.CharField(blank=True, default='', help_text='SAC code for this service', max_length=10, verbose_name='SAC Code'),
        ),
    ]
