# Generated by Django 5.2.6 on 2025-12-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_remove_serviceitem_hsn_code_serviceitem_sac_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='sac_code',
            field=models.CharField(blank=True, default='', help_text='SAC code for this service', max_length=10, null=True, verbose_name='SAC Code'),
        ),
    ]
