# Generated by Django 5.2.6 on 2026-02-02 10:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_tenantsubscription_orders_created'),
        ('invoicing', '0001_initial'),
        ('orders', '0005_remove_orderitem_priority_order_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True, verbose_name='Receipt Voucher Number')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='Receipt Date')),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Advance Amount (excl. GST)')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST rate applicable on advance', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GST Rate %')),
                ('tax_type', models.CharField(choices=[('INTRASTATE', 'Intrastate (CGST + SGST)'), ('INTERSTATE', 'Interstate (IGST)'), ('ZERO', 'Zero GST')], max_length=20, verbose_name='Tax Type')),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CGST Amount')),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='SGST Amount')),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IGST Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Amount (incl. GST)')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='Payment Mode')),
                ('deposited_to_bank', models.BooleanField(default=False, help_text='For cash payments - mark when deposited to bank', verbose_name='Deposited to Bank')),
                ('deposit_date', models.DateField(blank=True, null=True, verbose_name='Bank Deposit Date')),
                ('transaction_reference', models.CharField(blank=True, help_text='UPI ID, Card last 4 digits, Cheque number, etc.', max_length=100, verbose_name='Transaction Reference')),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount Adjusted')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Remaining Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_issued', models.BooleanField(default=True, verbose_name='Issued')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers', to='orders.customer', verbose_name='Customer')),
                ('order', models.ForeignKey(blank=True, help_text='Optional - link to order if advance is for specific order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers', to='orders.order', verbose_name='Order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_vouchers', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Receipt Voucher',
                'verbose_name_plural': 'Receipt Vouchers',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(max_length=50, unique=True, verbose_name='Refund Voucher Number')),
                ('refund_date', models.DateField(default=django.utils.timezone.now, verbose_name='Refund Date')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Refund Amount (excl. GST)')),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST Rate %')),
                ('tax_type', models.CharField(choices=[('INTRASTATE', 'Intrastate (CGST + SGST)'), ('INTERSTATE', 'Interstate (IGST)'), ('ZERO', 'Zero GST')], max_length=20, verbose_name='Tax Type')),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CGST Amount (Reversed)')),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='SGST Amount (Reversed)')),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IGST Amount (Reversed)')),
                ('total_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Refund (incl. GST reversal)')),
                ('refund_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI')], max_length=20, verbose_name='Refund Mode')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Transaction Reference')),
                ('reason', models.TextField(verbose_name='Reason for Refund')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.customer', verbose_name='Customer')),
                ('receipt_voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='financials.receiptvoucher', verbose_name='Original Receipt Voucher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_vouchers', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Refund Voucher',
                'verbose_name_plural': 'Refund Vouchers',
                'ordering': ['-refund_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Payment Number')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Payment Amount')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='Payment Mode')),
                ('deposited_to_bank', models.BooleanField(default=False, help_text='For cash payments - mark when deposited to bank', verbose_name='Deposited to Bank')),
                ('deposit_date', models.DateField(blank=True, null=True, verbose_name='Bank Deposit Date')),
                ('transaction_reference', models.CharField(blank=True, help_text='UPI ID, Card last 4 digits, Cheque number, etc.', max_length=100, verbose_name='Transaction Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoicing.invoice', verbose_name='Invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'payment_number'], name='financials__tenant__747bf3_idx'), models.Index(fields=['tenant', 'invoice'], name='financials__tenant__a45679_idx'), models.Index(fields=['tenant', 'payment_date'], name='financials__tenant__cbd527_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='receiptvoucher',
            index=models.Index(fields=['tenant', 'voucher_number'], name='financials__tenant__d8da8b_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucher',
            index=models.Index(fields=['tenant', 'customer'], name='financials__tenant__ea298c_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucher',
            index=models.Index(fields=['tenant', 'receipt_date'], name='financials__tenant__ecd820_idx'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['tenant', 'refund_number'], name='financials__tenant__03909f_idx'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['tenant', 'customer'], name='financials__tenant__9e4a78_idx'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['tenant', 'refund_date'], name='financials__tenant__679f7c_idx'),
        ),
    ]
