# Generated by Django 5.2.8 on 2026-01-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_tenantsubscription_orders_created'),
        ('financials', '0001_initial'),
        ('invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoicing.invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
