# Generated by Django 5.2.8 on 2026-02-04 01:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenantsubscription_orders_created'),
        ('financials', '0001_initial'),
        ('invoicing', '0002_alter_invoiceitem_item_type'),
        ('orders', '0005_remove_orderitem_priority_order_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Payment Refund Number')),
                ('refund_date', models.DateField(default=django.utils.timezone.now, verbose_name='Refund Date')),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount being refunded (without GST - GST already in invoice)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Refund Amount')),
                ('refund_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='Refund Mode')),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction ID, cheque number, etc.', max_length=100, verbose_name='Transaction Reference')),
                ('reason', models.TextField(help_text='Reason for refund (required for audit trail)', verbose_name='Reason for Refund')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_refunds_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refunds', to='orders.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refunds', to='invoicing.invoice', verbose_name='Invoice')),
                ('payment', models.ForeignKey(help_text='Invoice payment being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='financials.payment', verbose_name='Original Payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refunds', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'db_table': 'financials_payment_refund',
                'ordering': ['-refund_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'refund_date'], name='financials__tenant__d62723_idx'), models.Index(fields=['tenant', 'payment'], name='financials__tenant__41867e_idx'), models.Index(fields=['tenant', 'invoice'], name='financials__tenant__5da857_idx'), models.Index(fields=['tenant', 'customer'], name='financials__tenant__9b517d_idx')],
            },
        ),
    ]
