# Generated by Django 5.2.8 on 2026-01-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_tenantsubscription_orders_created'),
        ('financials', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvoucher',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers', to='orders.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Optional - link to order if advance is for specific order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_vouchers', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='refundvoucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='refundvoucher',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='refundvoucher',
            name='receipt_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='financials.receiptvoucher', verbose_name='Original Receipt Voucher'),
        ),
        migrations.AddField(
            model_name='refundvoucher',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_vouchers', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_number'], name='financials__tenant__747bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'invoice'], name='financials__tenant__a45679_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='financials__tenant__cbd527_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucher',
            index=models.Index(fields=['tenant', 'voucher_number'], name='financials__tenant__d8da8b_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucher',
            index=models.Index(fields=['tenant', 'customer'], name='financials__tenant__ea298c_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucher',
            index=models.Index(fields=['tenant', 'receipt_date'], name='financials__tenant__ecd820_idx'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['tenant', 'refund_number'], name='financials__tenant__03909f_idx'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['tenant', 'customer'], name='financials__tenant__9e4a78_idx'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['tenant', 'refund_date'], name='financials__tenant__679f7c_idx'),
        ),
    ]
