"""
Management command to create default subscription plans
"""

from django.core.management.base import BaseCommand
from decimal import Decimal
from core.models import SubscriptionPlan


class Command(BaseCommand):
    help = 'Create default subscription plans'
    
    def handle(self, *args, **options):
        self.stdout.write('Creating subscription plans...\n')
        
        plans = [
            # FREE TRIAL
            {
                'tier': 'FREE_TRIAL',
                'name': 'Free Trial',
                'description': '14-day trial with full access',
                'price_monthly': Decimal('0.00'),
                'price_yearly': Decimal('0.00'),
                'trial_days': 14,
                'display_order': 0,
                'max_orders_per_month': 20,
                'max_customers': 10,
                'max_employees': 5,
                'max_users': 2,
                'max_inventory_items': 50,
                'max_vendors': 5,
                'max_photos_per_order': 10,
                'allow_b2b_customers': True,
                'allow_measurement_profiles': True,
                'allow_gst_invoicing': True,
                'allow_item_discount': True,
                'allow_invoice_customization': 'ADVANCED',
                'allow_inventory': True,
                'allow_barcode_sku': True,
                'allow_purchase_orders': True,
                'allow_employee_management': True,
                'allow_attendance': 'QR_SCAN',
                'allow_leave_management': True,
                'allow_payroll': True,
                'allow_workflow': True,
                'max_workflow_stages': 14,
                'allow_task_assignment': True,
                'allow_qa_system': True,
                'allow_trial_feedback': True,
                'allow_order_qr': True,
                'allow_employee_qr': True,
                'report_types': ['sales', 'inventory', 'employee', 'workflow'],
                'allow_data_export': True,
                'allow_api_access': False,
                'support_level': 'EMAIL',
            },
            # STARTER
            {
                'tier': 'STARTER',
                'name': 'Starter',
                'description': 'For small shops',
                'price_monthly': Decimal('249.00'),
                'price_yearly': Decimal('2490.00'),
                'trial_days': 0,
                'display_order': 1,
                'max_orders_per_month': 40,
                'max_customers': 50,
                'max_employees': 0,
                'max_users': 1,
                'max_inventory_items': 0,
                'max_vendors': 0,
                'max_photos_per_order': 3,
                'allow_b2b_customers': False,
                'allow_measurement_profiles': False,
                'allow_gst_invoicing': False,
                'allow_item_discount': False,
                'allow_invoice_customization': 'NONE',
                'allow_inventory': False,
                'allow_barcode_sku': False,
                'allow_purchase_orders': False,
                'allow_employee_management': False,
                'allow_attendance': 'NONE',
                'allow_leave_management': False,
                'allow_payroll': False,
                'allow_workflow': False,
                'max_workflow_stages': 0,
                'allow_task_assignment': False,
                'allow_qa_system': False,
                'allow_trial_feedback': False,
                'allow_order_qr': True,
                'allow_employee_qr': False,
                'report_types': ['sales_basic'],
                'allow_data_export': False,
                'allow_api_access': False,
                'support_level': 'EMAIL',
            },
            # PRO
            {
                'tier': 'PRO',
                'name': 'Professional',
                'description': 'For growing shops',
                'price_monthly': Decimal('699.00'),
                'price_yearly': Decimal('6990.00'),
                'trial_days': 0,
                'display_order': 2,
                'is_popular': True,
                'max_orders_per_month': 150,
                'max_customers': 0,
                'max_employees': 8,
                'max_users': 5,
                'max_inventory_items': 100,
                'max_vendors': 10,
                'max_photos_per_order': 5,
                'allow_b2b_customers': True,
                'allow_measurement_profiles': True,
                'allow_gst_invoicing': True,
                'allow_item_discount': True,
                'allow_invoice_customization': 'BASIC',
                'allow_inventory': True,
                'allow_barcode_sku': True,
                'allow_purchase_orders': False,
                'allow_employee_management': True,
                'allow_attendance': 'MANUAL',
                'allow_leave_management': True,
                'allow_payroll': False,
                'allow_workflow': False,
                'max_workflow_stages': 0,
                'allow_task_assignment': False,
                'allow_qa_system': False,
                'allow_trial_feedback': False,
                'allow_order_qr': True,
                'allow_employee_qr': False,
                'report_types': ['sales', 'inventory', 'employee_basic'],
                'allow_data_export': True,
                'allow_api_access': False,
                'support_level': 'PRIORITY_EMAIL',
            },
            # BUSINESS
            {
                'tier': 'BUSINESS',
                'name': 'Business',
                'description': 'Complete workshop management',
                'price_monthly': Decimal('1499.00'),
                'price_yearly': Decimal('14990.00'),
                'trial_days': 0,
                'display_order': 3,
                'max_orders_per_month': 500,
                'max_customers': 0,
                'max_employees': 25,
                'max_users': 10,
                'max_inventory_items': 500,
                'max_vendors': 50,
                'max_photos_per_order': 10,
                'allow_b2b_customers': True,
                'allow_measurement_profiles': True,
                'allow_gst_invoicing': True,
                'allow_item_discount': True,
                'allow_invoice_customization': 'ADVANCED',
                'allow_inventory': True,
                'allow_barcode_sku': True,
                'allow_purchase_orders': True,
                'allow_employee_management': True,
                'allow_attendance': 'QR_SCAN',
                'allow_leave_management': True,
                'allow_payroll': True,
                'allow_workflow': True,
                'max_workflow_stages': 14,
                'allow_task_assignment': True,
                'allow_qa_system': True,
                'allow_trial_feedback': True,
                'allow_order_qr': True,
                'allow_employee_qr': True,
                'report_types': ['sales', 'inventory', 'employee', 'workflow', 'productivity'],
                'allow_data_export': True,
                'allow_api_access': False,
                'support_level': 'PHONE',
            },
            # ENTERPRISE
            {
                'tier': 'ENTERPRISE',
                'name': 'Enterprise',
                'description': 'Unlimited access',
                'price_monthly': Decimal('2999.00'),
                'price_yearly': Decimal('29990.00'),
                'trial_days': 0,
                'display_order': 4,
                'max_orders_per_month': 0,
                'max_customers': 0,
                'max_employees': 0,
                'max_users': 0,
                'max_inventory_items': 0,
                'max_vendors': 0,
                'max_photos_per_order': 20,
                'allow_b2b_customers': True,
                'allow_measurement_profiles': True,
                'allow_gst_invoicing': True,
                'allow_item_discount': True,
                'allow_invoice_customization': 'ADVANCED',
                'allow_inventory': True,
                'allow_barcode_sku': True,
                'allow_purchase_orders': True,
                'allow_employee_management': True,
                'allow_attendance': 'QR_SCAN',
                'allow_leave_management': True,
                'allow_payroll': True,
                'allow_workflow': True,
                'max_workflow_stages': 14,
                'allow_task_assignment': True,
                'allow_qa_system': True,
                'allow_trial_feedback': True,
                'allow_order_qr': True,
                'allow_employee_qr': True,
                'report_types': ['all'],
                'allow_data_export': True,
                'allow_api_access': True,
                'support_level': 'DEDICATED',
            },
        ]
        
        created_count = 0
        updated_count = 0
        
        for plan_data in plans:
            plan, created = SubscriptionPlan.objects.update_or_create(
                tier=plan_data['tier'],
                defaults=plan_data
            )
            
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'✓ Created: {plan.name}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'↻ Updated: {plan.name}'))
        
        self.stdout.write(self.style.SUCCESS(f'\n✓ Done! Created: {created_count}, Updated: {updated_count}'))