# Generated by Django 5.2.8 on 2026-01-23 05:38

import appointments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_tenantsubscription_orders_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[appointments.models.validate_phone_number])),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.tenant')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='appointment_tenant__30227b_idx'), models.Index(fields=['tenant', 'phone'], name='appointment_tenant__9027c5_idx'), models.Index(fields=['tenant', 'status'], name='appointment_tenant__f245c4_idx')],
            },
        ),
    ]
