# Generated by Django 5.2.8 on 2026-01-03 19:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255, verbose_name='Description')),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, verbose_name='HSN/SAC Code')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GST Rate %')),
                ('item_type', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICE', 'Service')], default='SERVICE', max_length=10, verbose_name='Item Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Invoice Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Invoice Status')),
                ('billing_name', models.CharField(max_length=200, verbose_name='Billing Name')),
                ('billing_address', models.TextField(verbose_name='Billing Address')),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(max_length=100, verbose_name='Billing State')),
                ('billing_pincode', models.CharField(blank=True, max_length=10)),
                ('billing_gstin', models.CharField(blank=True, max_length=15, verbose_name='Customer GSTIN')),
                ('shipping_name', models.CharField(blank=True, max_length=200, verbose_name='Shipping Name')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Shipping Address')),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100, verbose_name='Shipping State')),
                ('shipping_pincode', models.CharField(blank=True, max_length=10)),
                ('tax_type', models.CharField(choices=[('INTRASTATE', 'Intrastate (CGST + SGST)'), ('INTERSTATE', 'Interstate (IGST)'), ('ZERO', 'Zero GST')], max_length=20, verbose_name='Tax Type')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal (before tax)')),
                ('total_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total CGST')),
                ('total_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total SGST')),
                ('total_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total IGST')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Grand Total')),
                ('total_advance_adjusted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Advance Adjusted')),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Balance Due')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Paid')),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Remaining Balance')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20, verbose_name='Payment Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Terms & Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
    ]
