# Generated by Django 5.2.6 on 2026-01-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_initial'),
        ('orders', '0005_remove_orderitem_priority_order_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Optional - link to order if invoice created from order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='Order'),
        ),
    ]
