// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'customer.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Customer _$CustomerFromJson(Map<String, dynamic> json) => Customer(
  id: (json['id'] as num?)?.toInt(),
  name: json['name'] as String,
  phone: json['phone'] as String,
  whatsappNumber: json['whatsapp_number'] as String?,
  email: json['email'] as String?,
  gender: json['gender'] as String?,
  customerType: json['customer_type'] as String,
  businessName: json['business_name'] as String?,
  gstin: json['gstin'] as String?,
  pan: json['pan'] as String?,
  addressLine1: json['address_line1'] as String?,
  addressLine2: json['address_line2'] as String?,
  city: json['city'] as String?,
  state: json['state'] as String?,
  country: json['country'] as String?,
  pincode: json['pincode'] as String?,
  height: _toDouble(json['height']),
  weight: _toDouble(json['weight']),
  shoulderWidth: _toDouble(json['shoulder_width']),
  bustChest: _toDouble(json['bust_chest']),
  waist: _toDouble(json['waist']),
  hip: _toDouble(json['hip']),
  shoulder: _toDouble(json['shoulder']),
  sleeveLength: _toDouble(json['sleeve_length']),
  armhole: _toDouble(json['armhole']),
  garmentLength: _toDouble(json['garment_length']),
  frontNeckDepth: _toDouble(json['front_neck_depth']),
  backNeckDepth: _toDouble(json['back_neck_depth']),
  upperChest: _toDouble(json['upper_chest']),
  underBust: _toDouble(json['under_bust']),
  shoulderToApex: _toDouble(json['shoulder_to_apex']),
  bustPointDistance: _toDouble(json['bust_point_distance']),
  frontCross: _toDouble(json['front_cross']),
  backCross: _toDouble(json['back_cross']),
  lehengaLength: _toDouble(json['lehenga_length']),
  pantWaist: _toDouble(json['pant_waist']),
  ankleOpening: _toDouble(json['ankle_opening']),
  neckRound: _toDouble(json['neck_round']),
  stomachRound: _toDouble(json['stomach_round']),
  yokeWidth: _toDouble(json['yoke_width']),
  frontWidth: _toDouble(json['front_width']),
  backWidth: _toDouble(json['back_width']),
  trouserWaist: _toDouble(json['trouser_waist']),
  frontRise: _toDouble(json['front_rise']),
  backRise: _toDouble(json['back_rise']),
  bottomOpening: _toDouble(json['bottom_opening']),
  upperArmBicep: _toDouble(json['upper_arm_bicep']),
  sleeveLoose: _toDouble(json['sleeve_loose']),
  wristRound: _toDouble(json['wrist_round']),
  thigh: _toDouble(json['thigh']),
  knee: _toDouble(json['knee']),
  ankle: _toDouble(json['ankle']),
  rise: _toDouble(json['rise']),
  inseam: _toDouble(json['inseam']),
  outseam: _toDouble(json['outseam']),
  customField1: _toDouble(json['custom_field_1']),
  customField2: _toDouble(json['custom_field_2']),
  customField3: _toDouble(json['custom_field_3']),
  customField4: _toDouble(json['custom_field_4']),
  customField5: _toDouble(json['custom_field_5']),
  customField6: _toDouble(json['custom_field_6']),
  customField7: _toDouble(json['custom_field_7']),
  customField8: _toDouble(json['custom_field_8']),
  customField9: _toDouble(json['custom_field_9']),
  customField10: _toDouble(json['custom_field_10']),
  measurementNotes: json['measurement_notes'] as String?,
  notes: json['notes'] as String?,
  isActive: json['is_active'] as bool? ?? true,
  totalOrders: (json['total_orders'] as num?)?.toInt(),
  createdAt: json['created_at'] == null
      ? null
      : DateTime.parse(json['created_at'] as String),
  updatedAt: json['updated_at'] == null
      ? null
      : DateTime.parse(json['updated_at'] as String),
);

Map<String, dynamic> _$CustomerToJson(Customer instance) => <String, dynamic>{
  'id': instance.id,
  'name': instance.name,
  'phone': instance.phone,
  'whatsapp_number': instance.whatsappNumber,
  'email': instance.email,
  'gender': instance.gender,
  'customer_type': instance.customerType,
  'business_name': instance.businessName,
  'gstin': instance.gstin,
  'pan': instance.pan,
  'address_line1': instance.addressLine1,
  'address_line2': instance.addressLine2,
  'city': instance.city,
  'state': instance.state,
  'country': instance.country,
  'pincode': instance.pincode,
  'height': instance.height,
  'weight': instance.weight,
  'shoulder_width': instance.shoulderWidth,
  'bust_chest': instance.bustChest,
  'waist': instance.waist,
  'hip': instance.hip,
  'shoulder': instance.shoulder,
  'sleeve_length': instance.sleeveLength,
  'armhole': instance.armhole,
  'garment_length': instance.garmentLength,
  'front_neck_depth': instance.frontNeckDepth,
  'back_neck_depth': instance.backNeckDepth,
  'upper_chest': instance.upperChest,
  'under_bust': instance.underBust,
  'shoulder_to_apex': instance.shoulderToApex,
  'bust_point_distance': instance.bustPointDistance,
  'front_cross': instance.frontCross,
  'back_cross': instance.backCross,
  'lehenga_length': instance.lehengaLength,
  'pant_waist': instance.pantWaist,
  'ankle_opening': instance.ankleOpening,
  'neck_round': instance.neckRound,
  'stomach_round': instance.stomachRound,
  'yoke_width': instance.yokeWidth,
  'front_width': instance.frontWidth,
  'back_width': instance.backWidth,
  'trouser_waist': instance.trouserWaist,
  'front_rise': instance.frontRise,
  'back_rise': instance.backRise,
  'bottom_opening': instance.bottomOpening,
  'upper_arm_bicep': instance.upperArmBicep,
  'sleeve_loose': instance.sleeveLoose,
  'wrist_round': instance.wristRound,
  'thigh': instance.thigh,
  'knee': instance.knee,
  'ankle': instance.ankle,
  'rise': instance.rise,
  'inseam': instance.inseam,
  'outseam': instance.outseam,
  'custom_field_1': instance.customField1,
  'custom_field_2': instance.customField2,
  'custom_field_3': instance.customField3,
  'custom_field_4': instance.customField4,
  'custom_field_5': instance.customField5,
  'custom_field_6': instance.customField6,
  'custom_field_7': instance.customField7,
  'custom_field_8': instance.customField8,
  'custom_field_9': instance.customField9,
  'custom_field_10': instance.customField10,
  'measurement_notes': instance.measurementNotes,
  'notes': instance.notes,
  'is_active': instance.isActive,
  'total_orders': instance.totalOrders,
  'created_at': instance.createdAt?.toIso8601String(),
  'updated_at': instance.updatedAt?.toIso8601String(),
};

CustomerListResponse _$CustomerListResponseFromJson(
  Map<String, dynamic> json,
) => CustomerListResponse(
  count: (json['count'] as num).toInt(),
  next: json['next'] as String?,
  previous: json['previous'] as String?,
  results: (json['results'] as List<dynamic>)
      .map((e) => Customer.fromJson(e as Map<String, dynamic>))
      .toList(),
);

Map<String, dynamic> _$CustomerListResponseToJson(
  CustomerListResponse instance,
) => <String, dynamic>{
  'count': instance.count,
  'next': instance.next,
  'previous': instance.previous,
  'results': instance.results.map((e) => e.toJson()).toList(),
};
