# Generated by Django 5.2.8 on 2026-01-05 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreferencephoto',
            options={'verbose_name': 'Order Reference Photo', 'verbose_name_plural': 'Order Reference Photos'},
        ),
        migrations.AlterField(
            model_name='orderreferencephoto',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderreferencephoto',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_photos', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderreferencephoto',
            name='photo',
            field=models.ImageField(upload_to='order_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='orderreferencephoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
