# Generated by Django 5.2.8 on 2026-01-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderreferencephoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
    ]
