# Generated by Django 5.2.8 on 2026-01-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='priority',
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10, verbose_name='Priority'),
        ),
    ]
