# Generated by Django 5.2.8 on 2025-11-11 09:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plan display name', max_length=100)),
                ('plan_type', models.CharField(choices=[('FREE', 'Free Trial'), ('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], help_text='Unique plan identifier', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Monthly price in INR', max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, help_text='Yearly price in INR (usually discounted)', max_digits=10)),
                ('max_orders_per_month', models.IntegerField(blank=True, help_text='Maximum orders per month (null = unlimited)', null=True)),
                ('max_customers', models.IntegerField(blank=True, help_text='Maximum total customers (null = unlimited)', null=True)),
                ('max_staff_users', models.IntegerField(blank=True, help_text='Maximum staff users (null = unlimited)', null=True)),
                ('max_inventory_items', models.IntegerField(blank=True, help_text='Maximum inventory items (null = unlimited)', null=True)),
                ('has_inventory', models.BooleanField(default=False, help_text='Inventory management feature')),
                ('has_advanced_reports', models.BooleanField(default=False, help_text='Advanced reporting feature')),
                ('has_api_access', models.BooleanField(default=False, help_text='API access for integrations')),
                ('has_custom_fields', models.BooleanField(default=False, help_text='Custom field builder')),
                ('has_whatsapp_integration', models.BooleanField(default=False, help_text='WhatsApp notifications')),
                ('has_data_export', models.BooleanField(default=False, help_text='Export data to Excel/CSV')),
                ('has_multi_location', models.BooleanField(default=False, help_text='Multi-location support')),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Show in pricing page')),
                ('display_order', models.IntegerField(default=0, help_text='Order in pricing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shop name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly shop name', max_length=200, unique=True)),
                ('email', models.EmailField(help_text='Shop contact email', max_length=254)),
                ('phone_number', models.CharField(help_text='Shop contact phone', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, help_text='PAN Number', max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant (Shop)',
                'verbose_name_plural': 'Tenants (Shops)',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(help_text='User email (used for login)', max_length=254, unique=True)),
                ('name', models.CharField(help_text='Full name', max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Can access Django admin')),
                ('is_superuser', models.BooleanField(default=False, help_text='Has all permissions')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, help_text='Shop this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial Period'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='TRIAL', help_text='Current subscription status', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('current_month_orders', models.IntegerField(default=0, help_text='Orders created this month')),
                ('total_customers', models.IntegerField(default=0, help_text='Total customers')),
                ('total_staff_users', models.IntegerField(default=1, help_text='Total staff users')),
                ('total_inventory_items', models.IntegerField(default=0, help_text='Total inventory items')),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Trial expiration date', null=True)),
                ('current_period_start', models.DateTimeField(help_text='Current billing period start')),
                ('current_period_end', models.DateTimeField(help_text='Current billing period end')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Current subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.subscriptionplan')),
                ('tenant', models.OneToOneField(help_text='Shop this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Subscription',
                'verbose_name_plural': 'Tenant Subscriptions',
                'db_table': 'tenant_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
