# Generated by Django 5.2.8 on 2025-11-15 08:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantsubscription',
            options={'verbose_name': 'Tenant Subscription', 'verbose_name_plural': 'Tenant Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_advanced_reports',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_api_access',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_custom_fields',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_data_export',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_inventory',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_multi_location',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_whatsapp_integration',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_staff_users',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='current_month_orders',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='current_period_start',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='total_customers',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='total_inventory_items',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='total_staff_users',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='trial_ends_at',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_api_access',
            field=models.BooleanField(default=False, verbose_name='Allow API Access'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_attendance',
            field=models.CharField(choices=[('NONE', 'No Attendance'), ('MANUAL', 'Manual Entry'), ('QR_SCAN', 'QR Code Scanning')], default='NONE', max_length=20, verbose_name='Attendance System'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_b2b_customers',
            field=models.BooleanField(default=False, verbose_name='Allow B2B Customers'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_barcode_sku',
            field=models.BooleanField(default=False, verbose_name='Allow Barcode/SKU'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_data_export',
            field=models.BooleanField(default=False, verbose_name='Allow Data Export (Excel/PDF)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_employee_management',
            field=models.BooleanField(default=False, verbose_name='Allow Employee Management'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_employee_qr',
            field=models.BooleanField(default=False, verbose_name='Allow Employee QR Codes'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_gst_invoicing',
            field=models.BooleanField(default=False, verbose_name='Allow GST Invoicing'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_inventory',
            field=models.BooleanField(default=False, verbose_name='Allow Inventory Management'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_invoice_customization',
            field=models.CharField(choices=[('NONE', 'No Customization'), ('BASIC', 'Basic (Logo + Colors)'), ('ADVANCED', 'Advanced (Full Template)')], default='NONE', max_length=20, verbose_name='Invoice Customization'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_item_discount',
            field=models.BooleanField(default=False, verbose_name='Allow Item-Level Discount'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_leave_management',
            field=models.BooleanField(default=False, verbose_name='Allow Leave Management'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_measurement_profiles',
            field=models.BooleanField(default=False, verbose_name='Allow Measurement Profiles'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_order_qr',
            field=models.BooleanField(default=True, verbose_name='Allow Order QR Codes'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_payroll',
            field=models.BooleanField(default=False, verbose_name='Allow Payroll'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_purchase_orders',
            field=models.BooleanField(default=False, verbose_name='Allow Purchase Orders'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_qa_system',
            field=models.BooleanField(default=False, verbose_name='Allow QA System'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_task_assignment',
            field=models.BooleanField(default=False, verbose_name='Allow Task Assignment'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_trial_feedback',
            field=models.BooleanField(default=False, verbose_name='Allow Trial Feedback'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_workflow',
            field=models.BooleanField(default=False, verbose_name='Allow Workflow Tracking'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Mark as Popular'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_employees',
            field=models.IntegerField(default=0, help_text='0 = Unlimited', verbose_name='Max Employees'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_photos_per_order',
            field=models.IntegerField(default=3, verbose_name='Max Photos Per Order'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(default=1, verbose_name='Max User Accounts'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_vendors',
            field=models.IntegerField(default=0, help_text='0 = Unlimited', verbose_name='Max Vendors'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_workflow_stages',
            field=models.IntegerField(default=0, help_text='0 = Feature disabled', verbose_name='Max Workflow Stages'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='report_types',
            field=models.JSONField(default=list, help_text="List of report slugs: ['sales', 'inventory', 'employee']", verbose_name='Allowed Report Types'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='support_level',
            field=models.CharField(choices=[('EMAIL', 'Email Only'), ('PRIORITY_EMAIL', 'Priority Email'), ('PHONE', 'Phone + Email'), ('DEDICATED', 'Dedicated Support')], default='EMAIL', max_length=20, verbose_name='Support Level'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('STARTER', 'Starter'), ('PRO', 'Professional'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise')], default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='Plan Tier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=0, verbose_name='Trial Period (Days)'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='orders_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_customers',
            field=models.IntegerField(default=0, help_text='0 = Unlimited', verbose_name='Max Customers'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_inventory_items',
            field=models.IntegerField(default=0, help_text='0 = Unlimited', verbose_name='Max Inventory Items'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_orders_per_month',
            field=models.IntegerField(default=0, help_text='0 = Unlimited', verbose_name='Max Orders/Month'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Plan Name'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Price (INR)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, help_text='Annual pricing with discount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Yearly Price (INR)'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial Period'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], default='TRIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.tenant'),
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenantsubscription',
            table=None,
        ),
    ]
