# Generated by Django 5.2.8 on 2025-12-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tenantsubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_measurement_labels',
            field=models.JSONField(blank=True, default=dict, help_text='Labels for custom measurement fields (custom_1 to custom_10)', verbose_name='Custom Measurement Labels'),
        ),
    ]
