# Generated by Django 5.2.8 on 2025-12-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_custom_measurement_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='orders_created',
            field=models.IntegerField(default=0, help_text='Number of orders created in current billing period', verbose_name='Orders Created This Period'),
        ),
    ]
