# Generated by Django 5.2.8 on 2025-11-11 09:01

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('clock_in', models.DateTimeField(blank=True, null=True, verbose_name='Clock In')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='Clock Out')),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Regular Hours')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Overtime Hours')),
                ('break_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Break Hours')),
                ('total_working_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Regular + Overtime', max_digits=5, verbose_name='Total Working Hours')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('WEEKLY_OFF', 'Weekly Off'), ('HOLIDAY', 'Holiday'), ('LEAVE', 'On Leave')], default='PRESENT', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('clock_in_location', models.CharField(blank=True, max_length=200, verbose_name='Clock In Location')),
                ('clock_out_location', models.CharField(blank=True, max_length=200, verbose_name='Clock Out Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Cutting, Embroidery, Tailoring, Store', max_length=100, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='Enter manually: EMP-001, EMP-002, etc.', max_length=20, unique=True, verbose_name='Employee Code')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, verbose_name='Gender')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='Blood Group')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('WORKSHOP_MANAGER', 'Workshop Manager'), ('HR_MANAGER', 'HR Manager'), ('DESIGNER', 'Designer'), ('DEPARTMENT_MASTER', 'Department Master'), ('TAILOR', 'Tailor'), ('EMBROIDERY_WORKER', 'Embroidery Worker'), ('CUTTING_WORKER', 'Cutting Worker'), ('FINISHING_WORKER', 'Finishing Worker'), ('HELPER', 'Helper/Assistant'), ('STORE_MANAGER', 'Store Manager'), ('ACCOUNTANT', 'Accountant'), ('RECEPTIONIST', 'Receptionist'), ('DATA_ENTRY', 'Data Entry Clerk')], default='WORKER', max_length=30, verbose_name='Role')),
                ('specialization', models.CharField(blank=True, help_text='e.g., Tailor, Embroidery Worker, Cutting Master', max_length=100, verbose_name='Specialization')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('date_left', models.DateField(blank=True, null=True, verbose_name='Date Left')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('payment_type', models.CharField(choices=[('MONTHLY', 'Fixed Monthly Salary'), ('WEEKLY', 'Weekly Payment'), ('PIECE_RATE', 'Per Piece Rate'), ('HOURLY', 'Hourly Rate'), ('DAILY', 'Daily Wage'), ('MIXED', 'Salary + Piece Rate Bonus')], default='MONTHLY', max_length=20, verbose_name='Payment Type')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, help_text='For monthly/mixed payment types', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Salary (₹)')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Per hour rate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Hourly Rate (₹/hour)')),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Weekly Rate (₹)')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Daily Rate (₹)')),
                ('aadhar_number', models.CharField(blank=True, help_text='12-digit Aadhar number', max_length=12, verbose_name='Aadhar Number')),
                ('pan_number', models.CharField(blank=True, help_text='10-character PAN', max_length=10, verbose_name='PAN Number')),
                ('uan_number', models.CharField(blank=True, help_text='Universal Account Number for PF', max_length=12, verbose_name='UAN Number')),
                ('pf_number', models.CharField(blank=True, max_length=50, verbose_name='PF Account Number')),
                ('esi_number', models.CharField(blank=True, help_text='Employee State Insurance Number', max_length=17, verbose_name='ESI Number')),
                ('bank_account_name', models.CharField(blank=True, max_length=200, verbose_name='Account Holder Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank Name')),
                ('bank_branch', models.CharField(blank=True, max_length=200, verbose_name='Branch Name')),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, verbose_name='IFSC Code')),
                ('upi_id', models.CharField(blank=True, max_length=100, verbose_name='UPI ID')),
                ('nominee_name', models.CharField(blank=True, max_length=200, verbose_name='Nominee Name')),
                ('nominee_relationship', models.CharField(blank=True, help_text='e.g., Spouse, Father, Mother, Child', max_length=100, verbose_name='Nominee Relationship')),
                ('nominee_phone', models.CharField(blank=True, max_length=15, verbose_name='Nominee Phone Number')),
                ('nominee_aadhar', models.CharField(blank=True, max_length=12, verbose_name='Nominee Aadhar Number')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=15, verbose_name='Alternate Phone Number')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Relationship')),
                ('current_address', models.TextField(blank=True, verbose_name='Current Address')),
                ('permanent_address', models.TextField(blank=True, verbose_name='Permanent Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=6, verbose_name='PIN Code')),
                ('workshop_pin', models.CharField(blank=True, help_text='4-digit PIN for workshop tablet (Masters only)', max_length=4, verbose_name='Workshop PIN')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Photo')),
                ('qr_code', models.ImageField(blank=True, editable=False, null=True, upload_to='employees/qr_codes/', verbose_name='Employee QR Code')),
                ('aadhar_card_copy', models.FileField(blank=True, null=True, upload_to='employees/documents/aadhar/', verbose_name='Aadhar Card Copy')),
                ('pan_card_copy', models.FileField(blank=True, null=True, upload_to='employees/documents/pan/', verbose_name='PAN Card Copy')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='Department')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='Reports To')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.tenant', verbose_name='Tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='BreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('break_type', models.CharField(choices=[('LUNCH', 'Lunch Break'), ('TEA', 'Tea Break'), ('PRAYER', 'Prayer Break'), ('SMOKING', 'Smoking Break'), ('TOILET', 'Toilet Break'), ('OTHER', 'Other Break')], default='OTHER', max_length=20, verbose_name='Break Type')),
                ('start_time', models.DateTimeField(verbose_name='Break Start')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Break End')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Duration (minutes)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_logs', to='employees.attendance', verbose_name='Attendance Record')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_logs', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Break Log',
                'verbose_name_plural': 'Break Logs',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='Employee'),
        ),
        migrations.CreateModel(
            name='OvertimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Which day this OT should be credited to', verbose_name='OT Date')),
                ('ot_start', models.DateTimeField(verbose_name='OT Start Time')),
                ('ot_end', models.DateTimeField(verbose_name='OT End Time')),
                ('ot_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='OT Hours')),
                ('ot_type', models.CharField(choices=[('REGULAR_OT', 'Regular Overtime'), ('AFTER_MIDNIGHT', 'After Midnight OT'), ('EARLY_MORNING', 'Early Morning OT')], default='REGULAR_OT', max_length=20, verbose_name='OT Type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_logs', to='employees.attendance', verbose_name='Attendance Record')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_logs', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Overtime Log',
                'verbose_name_plural': 'Overtime Logs',
                'ordering': ['-date', '-ot_start'],
            },
        ),
        migrations.CreateModel(
            name='PieceRateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_item', models.DecimalField(decimal_places=2, help_text='Amount paid for completing one item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rate per Item')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_rates', to='employees.employee', verbose_name='Employee')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.itemcategory', verbose_name='Item Category')),
            ],
            options={
                'verbose_name': 'Piece Rate',
                'verbose_name_plural': 'Piece Rates',
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Opening Time')),
                ('closing_time', models.TimeField(default=datetime.time(19, 0), verbose_name='Closing Time')),
                ('lunch_start', models.TimeField(default=datetime.time(13, 0), verbose_name='Lunch Start')),
                ('lunch_end', models.TimeField(default=datetime.time(14, 0), verbose_name='Lunch End')),
                ('tea_break_1_start', models.TimeField(blank=True, default=datetime.time(11, 0), null=True, verbose_name='Tea Break 1 Start')),
                ('tea_break_1_end', models.TimeField(blank=True, default=datetime.time(11, 15), null=True, verbose_name='Tea Break 1 End')),
                ('tea_break_2_start', models.TimeField(blank=True, default=datetime.time(16, 0), null=True, verbose_name='Tea Break 2 Start')),
                ('tea_break_2_end', models.TimeField(blank=True, default=datetime.time(16, 15), null=True, verbose_name='Tea Break 2 End')),
                ('grace_period_minutes', models.IntegerField(default=10, help_text='Late arrival grace period', verbose_name='Grace Period (minutes)')),
                ('overtime_after_midnight_cutoff', models.TimeField(default=datetime.time(2, 0), help_text='OT after this time counts as next day (default: 2 AM)', verbose_name='OT Midnight Cutoff')),
                ('weekly_off_days', models.CharField(default='Sunday', help_text='Comma-separated: Sunday,Saturday', max_length=50, verbose_name='Weekly Off Days')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='OT rate multiplier (1.5 = 1.5x normal rate)', max_digits=3, verbose_name='OT Multiplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_settings', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'is_active'], name='employees_e_tenant__1e34d4_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role'], name='employees_e_role_caa0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employees_e_departm_99b42d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_code'], name='employees_e_employe_f8cfea_idx'),
        ),
        migrations.AddIndex(
            model_name='breaklog',
            index=models.Index(fields=['employee', 'date'], name='employees_b_employe_474dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='breaklog',
            index=models.Index(fields=['attendance'], name='employees_b_attenda_ca692b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='employees_a_employe_030d17_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='employees_a_date_b8bb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='employees_a_status_8f0e4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='overtimelog',
            index=models.Index(fields=['employee', 'date'], name='employees_o_employe_09953a_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimelog',
            index=models.Index(fields=['date'], name='employees_o_date_d625ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='piecerateitem',
            unique_together={('employee', 'item_category')},
        ),
    ]
