import 'package:flutter/material.dart';
import 'package:tailoring_web/core/theme/app_theme.dart';
import 'package:tailoring_web/core/api/api_client.dart';
import '../models/receipt_voucher.dart';
import '../models/refund_voucher.dart';
import '../services/payment_service.dart';

class IssueRefundDialog extends StatefulWidget {
  final ReceiptVoucher receiptVoucher;
  final VoidCallback onRefundIssued;

  const IssueRefundDialog({
    Key? key,
    required this.receiptVoucher,
    required this.onRefundIssued,
  }) : super(key: key);

  @override
  State<IssueRefundDialog> createState() => _IssueRefundDialogState();
}

class _IssueRefundDialogState extends State<IssueRefundDialog> {
  final _formKey = GlobalKey<FormState>();
  final _paymentService = PaymentService();

  late TextEditingController _refundAmountController;
  late TextEditingController _transactionRefController;
  late TextEditingController _reasonController;
  late TextEditingController _notesController;

  DateTime _refundDate = DateTime.now();
  String _refundMode = 'CASH';
  bool _isSaving = false;

  // Calculated values
  double _refundAmount = 0.0;
  double _gstAmount = 0.0;
  double _totalRefund = 0.0;

  @override
  void initState() {
    super.initState();
    _refundAmountController = TextEditingController();
    _transactionRefController = TextEditingController();
    _reasonController = TextEditingController();
    _notesController = TextEditingController();

    // Set max refund amount to receipt total
    _refundAmountController.text = widget.receiptVoucher.totalAmount
        .toStringAsFixed(2);
    _calculateRefund();

    _refundAmountController.addListener(_calculateRefund);
  }

  @override
  void dispose() {
    _refundAmountController.dispose();
    _transactionRefController.dispose();
    _reasonController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _calculateRefund() {
    setState(() {
      _refundAmount = double.tryParse(_refundAmountController.text) ?? 0.0;

      // Calculate GST reversal based on original receipt's GST rate
      // The refund amount is the total (including GST), we need to extract base + GST
      if (widget.receiptVoucher.gstRate > 0) {
        // If original had GST, calculate proportional GST reversal
        double gstMultiplier = widget.receiptVoucher.gstRate / 100;
        double baseAmount = _refundAmount / (1 + gstMultiplier);
        _gstAmount = _refundAmount - baseAmount;
        _totalRefund = _refundAmount;
      } else {
        // No GST on original receipt
        _gstAmount = 0.0;
        _totalRefund = _refundAmount;
      }
    });
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _refundDate,
      firstDate: widget.receiptVoucher.receiptDate,
      lastDate: DateTime.now().add(const Duration(days: 30)),
    );

    if (picked != null && picked != _refundDate) {
      setState(() {
        _refundDate = picked;
      });
    }
  }

  Future<void> _issueRefund() async {
    if (!_formKey.currentState!.validate()) return;

    if (_reasonController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please provide a reason for refund'),
          backgroundColor: AppTheme.danger,
        ),
      );
      return;
    }

    setState(() => _isSaving = true);

    try {
      // Calculate GST breakdown
      double cgst = 0.0;
      double sgst = 0.0;
      double igst = 0.0;
      double baseAmount = _refundAmount;

      if (widget.receiptVoucher.gstRate > 0) {
        double gstMultiplier = widget.receiptVoucher.gstRate / 100;
        baseAmount = _refundAmount / (1 + gstMultiplier);
        double totalGst = _refundAmount - baseAmount;

        if (widget.receiptVoucher.taxType == 'CGST_SGST') {
          cgst = totalGst / 2;
          sgst = totalGst / 2;
        } else {
          igst = totalGst;
        }
      }

      final refund = RefundVoucher(
        refundNumber: '', // Will be generated by backend
        refundDate: _refundDate,
        receiptVoucher: widget.receiptVoucher.id!,
        customer: widget.receiptVoucher.customer,
        refundAmount: baseAmount,
        gstRate: widget.receiptVoucher.gstRate,
        taxType: widget.receiptVoucher.taxType,
        cgstAmount: cgst,
        sgstAmount: sgst,
        igstAmount: igst,
        totalRefund: _refundAmount,
        refundMode: _refundMode,
        transactionReference: _transactionRefController.text.trim(),
        reason: _reasonController.text.trim(),
        notes: _notesController.text.trim(),
      );

      await _paymentService.createRefundVoucher(refund);

      if (mounted) {
        Navigator.pop(context);
        widget.onRefundIssued();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Refund issued successfully'),
            backgroundColor: AppTheme.success,
          ),
        );
      }
    } on ApiException catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(e.message), backgroundColor: AppTheme.danger),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to issue refund: $e'),
            backgroundColor: AppTheme.danger,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isSaving = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      child: Container(
        constraints: const BoxConstraints(maxWidth: 600),
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Form(
              key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Header
                  Row(
                    children: [
                      const Icon(
                        Icons.money_off,
                        color: AppTheme.danger,
                        size: 24,
                      ),
                      const SizedBox(width: 12),
                      Text('Issue Refund', style: AppTheme.heading2),
                      const Spacer(),
                      IconButton(
                        icon: const Icon(Icons.close),
                        onPressed: () => Navigator.pop(context),
                      ),
                    ],
                  ),
                  const SizedBox(height: 24),

                  // Original Receipt Info
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: AppTheme.backgroundGrey,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Original Receipt', style: AppTheme.bodySmallBold),
                        const SizedBox(height: 8),
                        _buildInfoRow(
                          'Receipt #',
                          widget.receiptVoucher.voucherNumber,
                        ),
                        _buildInfoRow(
                          'Date',
                          widget.receiptVoucher.formattedReceiptDate,
                        ),
                        _buildInfoRow(
                          'Amount',
                          widget.receiptVoucher.formattedTotalAmount,
                        ),
                        if (widget.receiptVoucher.gstRate > 0)
                          _buildInfoRow(
                            'GST',
                            '${widget.receiptVoucher.gstRate.toStringAsFixed(0)}% (${widget.receiptVoucher.taxType})',
                          ),
                      ],
                    ),
                  ),

                  const SizedBox(height: 24),
                  const Divider(),
                  const SizedBox(height: 24),

                  // Refund Date
                  Text('Refund Date', style: AppTheme.heading3),
                  const SizedBox(height: 12),
                  InkWell(
                    onTap: () => _selectDate(context),
                    child: InputDecorator(
                      decoration: const InputDecoration(
                        border: OutlineInputBorder(),
                        suffixIcon: Icon(Icons.calendar_today, size: 18),
                      ),
                      child: Text(
                        _formatDate(_refundDate),
                        style: AppTheme.bodyMedium,
                      ),
                    ),
                  ),

                  const SizedBox(height: 24),

                  // Refund Amount
                  Text('Refund Amount', style: AppTheme.heading3),
                  const SizedBox(height: 12),
                  TextFormField(
                    controller: _refundAmountController,
                    keyboardType: const TextInputType.numberWithOptions(
                      decimal: true,
                    ),
                    decoration: InputDecoration(
                      prefixText: '₹ ',
                      border: const OutlineInputBorder(),
                      hintText: '0.00',
                      helperText:
                          'Maximum: ₹${widget.receiptVoucher.totalAmount.toStringAsFixed(2)}',
                    ),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter refund amount';
                      }
                      final amount = double.tryParse(value);
                      if (amount == null || amount <= 0) {
                        return 'Please enter a valid amount';
                      }
                      if (amount > widget.receiptVoucher.totalAmount) {
                        return 'Amount cannot exceed receipt total';
                      }
                      return null;
                    },
                  ),

                  const SizedBox(height: 24),

                  // GST Breakdown
                  if (widget.receiptVoucher.gstRate > 0) ...[
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: AppTheme.backgroundGrey,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'GST Calculation',
                            style: AppTheme.bodySmallBold,
                          ),
                          const SizedBox(height: 8),
                          _buildInfoRow(
                            'Base Amount',
                            '₹${(_refundAmount / (1 + widget.receiptVoucher.gstRate / 100)).toStringAsFixed(2)}',
                          ),
                          _buildInfoRow(
                            'GST (${widget.receiptVoucher.gstRate.toStringAsFixed(0)}%)',
                            '₹${_gstAmount.toStringAsFixed(2)}',
                          ),
                          const Divider(height: 16),
                          _buildInfoRow(
                            'Total Refund',
                            '₹${_totalRefund.toStringAsFixed(2)}',
                            isBold: true,
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),
                  ],

                  // Refund Mode
                  Text('Refund Mode', style: AppTheme.heading3),
                  const SizedBox(height: 12),
                  DropdownButtonFormField<String>(
                    value: _refundMode,
                    decoration: const InputDecoration(
                      border: OutlineInputBorder(),
                    ),
                    items: const [
                      DropdownMenuItem(value: 'CASH', child: Text('Cash')),
                      DropdownMenuItem(
                        value: 'BANK_TRANSFER',
                        child: Text('Bank Transfer'),
                      ),
                      DropdownMenuItem(value: 'UPI', child: Text('UPI')),
                    ],
                    onChanged: (value) {
                      if (value != null) {
                        setState(() => _refundMode = value);
                      }
                    },
                  ),

                  const SizedBox(height: 24),

                  // Transaction Reference
                  if (_refundMode != 'CASH') ...[
                    Text('Transaction Reference', style: AppTheme.heading3),
                    const SizedBox(height: 12),
                    TextFormField(
                      controller: _transactionRefController,
                      decoration: const InputDecoration(
                        border: OutlineInputBorder(),
                        hintText: 'Transaction ID / Reference Number',
                      ),
                    ),
                    const SizedBox(height: 24),
                  ],

                  // Reason (Required)
                  Text('Reason for Refund *', style: AppTheme.heading3),
                  const SizedBox(height: 12),
                  TextFormField(
                    controller: _reasonController,
                    maxLines: 3,
                    decoration: const InputDecoration(
                      border: OutlineInputBorder(),
                      hintText:
                          'e.g., Customer cancelled order, Order not completed',
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Reason is required';
                      }
                      return null;
                    },
                  ),

                  const SizedBox(height: 24),

                  // Notes (Optional)
                  Text('Notes (Optional)', style: AppTheme.heading3),
                  const SizedBox(height: 12),
                  TextFormField(
                    controller: _notesController,
                    maxLines: 2,
                    decoration: const InputDecoration(
                      border: OutlineInputBorder(),
                      hintText: 'Additional notes...',
                    ),
                  ),

                  const SizedBox(height: 32),

                  // Action Buttons
                  Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      TextButton(
                        onPressed: _isSaving
                            ? null
                            : () => Navigator.pop(context),
                        child: const Text('Cancel'),
                      ),
                      const SizedBox(width: 12),
                      ElevatedButton(
                        onPressed: _isSaving ? null : _issueRefund,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppTheme.danger,
                          padding: const EdgeInsets.symmetric(
                            horizontal: 32,
                            vertical: 14,
                          ),
                        ),
                        child: _isSaving
                            ? const SizedBox(
                                width: 20,
                                height: 20,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  valueColor: AlwaysStoppedAnimation<Color>(
                                    Colors.white,
                                  ),
                                ),
                              )
                            : const Text('Issue Refund'),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildInfoRow(String label, String value, {bool isBold = false}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: AppTheme.bodySmall.copyWith(
              fontWeight: isBold ? FontWeight.w600 : FontWeight.normal,
            ),
          ),
          Text(
            value,
            style: AppTheme.bodyMedium.copyWith(
              fontWeight: isBold ? FontWeight.w600 : FontWeight.normal,
            ),
          ),
        ],
      ),
    );
  }

  String _formatDate(DateTime date) {
    return '${date.day.toString().padLeft(2, '0')}-${date.month.toString().padLeft(2, '0')}-${date.year}';
  }
}
