import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:tailoring_web/core/theme/app_theme.dart';
import 'package:tailoring_web/core/api/api_client.dart';
import 'package:tailoring_web/features/financials/models/receipt_voucher.dart';
import 'package:tailoring_web/features/financials/services/payment_service.dart';

class RecordPaymentDialog extends StatefulWidget {
  final Map<String, dynamic> orderData;
  final Function(ReceiptVoucher) onPaymentRecorded;

  const RecordPaymentDialog({
    Key? key,
    required this.orderData,
    required this.onPaymentRecorded,
  }) : super(key: key);

  @override
  State<RecordPaymentDialog> createState() => _RecordPaymentDialogState();
}

class _RecordPaymentDialogState extends State<RecordPaymentDialog> {
  final _formKey = GlobalKey<FormState>();
  final _paymentService = PaymentService();

  // Form controllers
  final _amountController = TextEditingController();
  final _transactionRefController = TextEditingController();
  final _notesController = TextEditingController();

  // Form values
  DateTime _paymentDate = DateTime.now();
  String _paymentMode = 'CASH';
  double _gstRate = 0.0;
  bool _applyGST = false;
  bool _isSubmitting = false;

  // Calculated values
  double _cgst = 0.0;
  double _sgst = 0.0;
  double _totalAmount = 0.0;

  @override
  void initState() {
    super.initState();
    _amountController.addListener(_calculateTotals);
  }

  @override
  void dispose() {
    _amountController.dispose();
    _transactionRefController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _calculateTotals() {
    final amount = double.tryParse(_amountController.text) ?? 0.0;

    if (_applyGST && _gstRate > 0) {
      _cgst = (amount * _gstRate / 100) / 2;
      _sgst = (amount * _gstRate / 100) / 2;
      _totalAmount = amount + (_cgst + _sgst);
    } else {
      _cgst = 0.0;
      _sgst = 0.0;
      _totalAmount = amount;
    }

    setState(() {});
  }

  int _getIntValue(dynamic value) {
    if (value == null) return 0;
    if (value is int) return value;
    if (value is String) return int.tryParse(value) ?? 0;
    return 0;
  }

  double _getDoubleValue(dynamic value) {
    if (value == null) return 0.0;
    if (value is double) return value;
    if (value is int) return value.toDouble();
    if (value is String) return double.tryParse(value) ?? 0.0;
    return 0.0;
  }

  Future<void> _submitPayment() async {
    if (!_formKey.currentState!.validate()) return;

    final amount = double.tryParse(_amountController.text);
    if (amount == null || amount <= 0) {
      _showError('Please enter a valid amount');
      return;
    }

    // Get balance due with proper type handling
    final orderTotal = _getDoubleValue(widget.orderData['estimated_total']);
    final advanceReceived = _getDoubleValue(
      widget.orderData['advance_received'],
    );
    final balanceDue = orderTotal - advanceReceived;

    if (amount > balanceDue) {
      _showError(
        'Payment amount (₹${amount.toStringAsFixed(2)}) exceeds balance due (₹${balanceDue.toStringAsFixed(2)})',
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final customerId = _getIntValue(widget.orderData['customer']);
      final orderId = _getIntValue(widget.orderData['id']);

      if (customerId == 0 || orderId == 0) {
        throw Exception('Invalid customer or order ID');
      }

      final receiptVoucher = ReceiptVoucher(
        voucherNumber: '', // Auto-generated by backend
        receiptDate: _paymentDate,
        customer: customerId,
        order: orderId,
        advanceAmount: amount,
        gstRate: _applyGST ? _gstRate : 0.0,
        totalAmount: _totalAmount,
        paymentMode: _paymentMode,
        transactionReference: _transactionRefController.text.trim().isNotEmpty
            ? _transactionRefController.text.trim()
            : null,
        notes: _notesController.text.trim().isNotEmpty
            ? _notesController.text.trim()
            : null,
      );

      final createdVoucher = await _paymentService.createReceiptVoucher(
        receiptVoucher,
      );

      if (mounted) {
        Navigator.pop(context);
        widget.onPaymentRecorded(createdVoucher);
        _showSuccess('Payment recorded successfully');
      }
    } on ApiException catch (e) {
      if (mounted) {
        _showError(e.message);
      }
    } catch (e) {
      if (mounted) {
        _showError('Failed to record payment: $e');
      }
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message), backgroundColor: AppTheme.danger),
    );
  }

  void _showSuccess(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message), backgroundColor: AppTheme.success),
    );
  }

  @override
  Widget build(BuildContext context) {
    final orderTotal = _getDoubleValue(widget.orderData['estimated_total']);
    final advanceReceived = _getDoubleValue(
      widget.orderData['advance_received'],
    );
    final balanceDue = orderTotal - advanceReceived;

    return Dialog(
      child: Container(
        width: 600,
        constraints: const BoxConstraints(maxHeight: 700),
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Form(
              key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Header
                  Row(
                    children: [
                      const Icon(Icons.payment, color: AppTheme.primaryBlue),
                      const SizedBox(width: 12),
                      const Text('Record Payment', style: AppTheme.heading2),
                      const Spacer(),
                      IconButton(
                        icon: const Icon(Icons.close),
                        onPressed: () => Navigator.pop(context),
                      ),
                    ],
                  ),
                  const Divider(height: 32),

                  // Order Summary
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: AppTheme.backgroundGrey,
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _buildSummaryRow(
                          'Order Total',
                          '₹${orderTotal.toStringAsFixed(2)}',
                        ),
                        const SizedBox(height: 8),
                        _buildSummaryRow(
                          'Paid',
                          '₹${advanceReceived.toStringAsFixed(2)}',
                          AppTheme.success,
                        ),
                        const SizedBox(height: 8),
                        _buildSummaryRow(
                          'Balance Due',
                          '₹${balanceDue.toStringAsFixed(2)}',
                          AppTheme.warning,
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 24),

                  // Payment Date & Mode
                  Row(
                    children: [
                      Expanded(
                        child: InkWell(
                          onTap: () async {
                            final date = await showDatePicker(
                              context: context,
                              initialDate: _paymentDate,
                              firstDate: DateTime(2020),
                              lastDate: DateTime.now(),
                            );
                            if (date != null) {
                              setState(() => _paymentDate = date);
                            }
                          },
                          child: InputDecorator(
                            decoration: const InputDecoration(
                              labelText: 'Payment Date',
                              border: OutlineInputBorder(),
                              suffixIcon: Icon(Icons.calendar_today),
                            ),
                            child: Text(
                              '${_paymentDate.day.toString().padLeft(2, '0')}-${_paymentDate.month.toString().padLeft(2, '0')}-${_paymentDate.year}',
                              style: AppTheme.bodyMedium,
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: DropdownButtonFormField<String>(
                          value: _paymentMode,
                          decoration: const InputDecoration(
                            labelText: 'Payment Mode',
                            border: OutlineInputBorder(),
                          ),
                          items: const [
                            DropdownMenuItem(
                              value: 'CASH',
                              child: Text('Cash'),
                            ),
                            DropdownMenuItem(value: 'UPI', child: Text('UPI')),
                            DropdownMenuItem(
                              value: 'CARD',
                              child: Text('Card'),
                            ),
                            DropdownMenuItem(
                              value: 'BANK_TRANSFER',
                              child: Text('Bank Transfer'),
                            ),
                          ],
                          onChanged: (value) {
                            if (value != null)
                              setState(() => _paymentMode = value);
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // Amount
                  TextFormField(
                    controller: _amountController,
                    decoration: InputDecoration(
                      labelText: 'Payment Amount',
                      prefixText: '₹ ',
                      border: const OutlineInputBorder(),
                      helperText: 'Max: ₹${balanceDue.toStringAsFixed(2)}',
                    ),
                    keyboardType: const TextInputType.numberWithOptions(
                      decimal: true,
                    ),
                    inputFormatters: [
                      FilteringTextInputFormatter.allow(
                        RegExp(r'^\d+\.?\d{0,2}'),
                      ),
                    ],
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter amount';
                      }
                      final amount = double.tryParse(value);
                      if (amount == null || amount <= 0) {
                        return 'Please enter valid amount';
                      }
                      if (amount > balanceDue) {
                        return 'Amount exceeds balance due';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),

                  // GST Toggle
                  CheckboxListTile(
                    title: const Text('Apply GST', style: AppTheme.bodyMedium),
                    value: _applyGST,
                    onChanged: (value) {
                      setState(() {
                        _applyGST = value ?? false;
                        _calculateTotals();
                      });
                    },
                    controlAffinity: ListTileControlAffinity.leading,
                    contentPadding: EdgeInsets.zero,
                  ),

                  // GST Rate
                  if (_applyGST) ...[
                    const SizedBox(height: 8),
                    DropdownButtonFormField<double>(
                      value: _gstRate,
                      decoration: const InputDecoration(
                        labelText: 'GST Rate',
                        border: OutlineInputBorder(),
                      ),
                      items: const [
                        DropdownMenuItem(value: 0.0, child: Text('0%')),
                        DropdownMenuItem(value: 5.0, child: Text('5%')),
                        DropdownMenuItem(value: 12.0, child: Text('12%')),
                        DropdownMenuItem(value: 18.0, child: Text('18%')),
                        DropdownMenuItem(value: 28.0, child: Text('28%')),
                      ],
                      onChanged: (value) {
                        if (value != null) {
                          setState(() {
                            _gstRate = value;
                            _calculateTotals();
                          });
                        }
                      },
                    ),
                  ],

                  // Tax Breakdown
                  if (_applyGST && _gstRate > 0) ...[
                    const SizedBox(height: 16),
                    Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: AppTheme.primaryBlue.withOpacity(0.05),
                        borderRadius: BorderRadius.circular(4),
                        border: Border.all(
                          color: AppTheme.primaryBlue.withOpacity(0.2),
                        ),
                      ),
                      child: Column(
                        children: [
                          _buildTaxRow(
                            'CGST (${(_gstRate / 2).toStringAsFixed(1)}%)',
                            _cgst,
                          ),
                          const SizedBox(height: 4),
                          _buildTaxRow(
                            'SGST (${(_gstRate / 2).toStringAsFixed(1)}%)',
                            _sgst,
                          ),
                          const Divider(height: 16),
                          _buildTaxRow(
                            'Total Amount',
                            _totalAmount,
                            bold: true,
                          ),
                        ],
                      ),
                    ),
                  ],
                  const SizedBox(height: 16),

                  // Transaction Reference
                  if (_paymentMode != 'CASH') ...[
                    TextFormField(
                      controller: _transactionRefController,
                      decoration: const InputDecoration(
                        labelText: 'Transaction Reference',
                        border: OutlineInputBorder(),
                        hintText: 'e.g., UPI ID, Transaction ID',
                      ),
                    ),
                    const SizedBox(height: 16),
                  ],

                  // Notes
                  TextFormField(
                    controller: _notesController,
                    decoration: const InputDecoration(
                      labelText: 'Notes (Optional)',
                      border: OutlineInputBorder(),
                    ),
                    maxLines: 2,
                  ),
                  const SizedBox(height: 24),

                  // Actions
                  Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      TextButton(
                        onPressed: _isSubmitting
                            ? null
                            : () => Navigator.pop(context),
                        child: const Text('Cancel'),
                      ),
                      const SizedBox(width: 12),
                      ElevatedButton.icon(
                        onPressed: _isSubmitting ? null : _submitPayment,
                        icon: _isSubmitting
                            ? const SizedBox(
                                width: 20,
                                height: 20,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  valueColor: AlwaysStoppedAnimation<Color>(
                                    Colors.white,
                                  ),
                                ),
                              )
                            : const Icon(Icons.check),
                        label: Text(
                          _isSubmitting ? 'Recording...' : 'Record Payment',
                        ),
                        style: ElevatedButton.styleFrom(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 24,
                            vertical: 16,
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSummaryRow(String label, String value, [Color? color]) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(label, style: AppTheme.bodyMedium),
        Text(
          value,
          style: AppTheme.bodyMedium.copyWith(
            fontWeight: FontWeight.w600,
            color: color,
          ),
        ),
      ],
    );
  }

  Widget _buildTaxRow(String label, double amount, {bool bold = false}) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: AppTheme.bodySmall.copyWith(
            fontWeight: bold ? FontWeight.w600 : FontWeight.normal,
          ),
        ),
        Text(
          '₹${amount.toStringAsFixed(2)}',
          style: AppTheme.bodySmall.copyWith(
            fontWeight: bold ? FontWeight.w600 : FontWeight.normal,
          ),
        ),
      ],
    );
  }
}
