import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/layouts/main_layout.dart';
import '../../../core/theme/app_theme.dart';
import '../providers/order_provider.dart';
import '../../items/providers/item_provider.dart';
import '../../customers/models/customer.dart';

import '../widgets/customer_autocomplete.dart';

import '../models/order.dart';
import '../models/order_item.dart';
import '../widgets/order_items_table.dart';
import '../widgets/order_summary_panel.dart';
import '../widgets/reference_photos_section.dart';

/// Create Order Screen
/// Split layout with form on left and summary on right
class CreateOrderScreen extends StatefulWidget {
  final Customer? preSelectedCustomer;

  const CreateOrderScreen({super.key, this.preSelectedCustomer});

  @override
  State<CreateOrderScreen> createState() => _CreateOrderScreenState();
}

class _CreateOrderScreenState extends State<CreateOrderScreen> {
  Customer? _selectedCustomer;
  final List<OrderItem> _orderItems = [];
  final List<ReferencePhotoData> _referencePhotos = [];
  DateTime _expectedDeliveryDate = DateTime.now().add(const Duration(days: 7));
  bool _isTaxInclusive = false;
  bool _isLoading = false;

  final _orderSummaryController = TextEditingController();
  final _customerInstructionsController = TextEditingController();

  @override
  void initState() {
    super.initState();
    _selectedCustomer = widget.preSelectedCustomer;

    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<ItemProvider>().fetchItems();
    });
  }

  @override
  void dispose() {
    _orderSummaryController.dispose();
    _customerInstructionsController.dispose();
    super.dispose();
  }

  Future<void> _selectDeliveryDate() async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _expectedDeliveryDate,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (picked != null && picked != _expectedDeliveryDate) {
      setState(() {
        _expectedDeliveryDate = picked;
      });
    }
  }

  void _onTaxModeChanged(bool isTaxInclusive) {
    setState(() {
      _isTaxInclusive = isTaxInclusive;
      // Recalculate all items for new tax mode
      _orderItems.clear();
      _orderItems.addAll(
        _orderItems
            .map(
              (item) =>
                  item.recalculateForTaxMode(isTaxInclusive: isTaxInclusive),
            )
            .toList(),
      );
    });
  }

  Future<void> _saveOrder() async {
    if (_selectedCustomer == null || _orderItems.isEmpty) return;

    setState(() => _isLoading = true);

    try {
      // Calculate totals
      final itemsSubtotal = _orderItems.fold<double>(
        0.0,
        (sum, item) => sum + (item.quantity * item.unitPrice),
      );

      final itemDiscounts = _orderItems.fold<double>(
        0.0,
        (sum, item) => sum + item.discount,
      );

      final taxableValue = itemsSubtotal - itemDiscounts;

      final totalTax = _orderItems.fold<double>(
        0.0,
        (sum, item) => sum + item.taxAmount,
      );

      final grandTotal = _isTaxInclusive
          ? taxableValue
          : (taxableValue + totalTax);

      // Create order object
      final order = Order(
        orderNumber: '', // Auto-generated by backend
        customerId: _selectedCustomer!.id!,
        orderDate: DateTime.now(),
        expectedDeliveryDate: _expectedDeliveryDate,
        orderStatus: 'DRAFT',
        deliveryStatus: 'NOT_STARTED',
        estimatedTotal: grandTotal,
        orderSummary: _orderSummaryController.text,
        customerInstructions: _customerInstructionsController.text,
        items: _orderItems,
      );

      // Create order via provider
      final createdOrder = await context.read<OrderProvider>().createOrder(
        order,
      );

      if (createdOrder != null) {
        // Upload reference photos if any
        if (_referencePhotos.isNotEmpty && createdOrder.id != null) {
          for (final photo in _referencePhotos) {
            await context.read<OrderProvider>().uploadReferencePhoto(
              createdOrder.id!,
              photo.path,
            );
          }
        }

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                'Order ${createdOrder.orderNumber} created successfully!',
              ),
              backgroundColor: AppTheme.success,
            ),
          );
          Navigator.pop(context, true);
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                context.read<OrderProvider>().errorMessage ??
                    'Failed to create order',
              ),
              backgroundColor: AppTheme.danger,
            ),
          );
        }
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return MainLayout(
      currentRoute: '/orders',
      child: Column(
        children: [
          _buildHeader(),
          Expanded(child: _buildSplitLayout()),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.all(AppTheme.space5),
      decoration: const BoxDecoration(
        color: AppTheme.backgroundWhite,
        border: Border(bottom: BorderSide(color: AppTheme.borderLight)),
      ),
      child: Row(
        children: [
          IconButton(
            icon: const Icon(Icons.arrow_back),
            onPressed: () => Navigator.pop(context),
          ),
          const SizedBox(width: AppTheme.space3),
          const Text('Create Order', style: AppTheme.heading2),
          const Spacer(),
          if (_isLoading)
            const SizedBox(
              width: 20,
              height: 20,
              child: CircularProgressIndicator(strokeWidth: 2),
            ),
        ],
      ),
    );
  }

  Widget _buildSplitLayout() {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Left side - Form
        Expanded(
          flex: 7,
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(AppTheme.space5),
            child: Column(
              children: [
                _buildCustomerSection(),
                const SizedBox(height: AppTheme.space4),
                _buildOrderDetailsSection(),
                const SizedBox(height: AppTheme.space4),
                _buildItemsSection(),
                const SizedBox(height: AppTheme.space4),
                ReferencePhotosSection(
                  photos: _referencePhotos,
                  onPhotosChanged: (photos) {
                    setState(() {
                      _referencePhotos.clear();
                      _referencePhotos.addAll(photos);
                    });
                  },
                ),
                const SizedBox(height: AppTheme.space4),
                _buildNotesSection(),
              ],
            ),
          ),
        ),

        // Right side - Summary Panel
        OrderSummaryPanel(
          items: _orderItems,
          isTaxInclusive: _isTaxInclusive,
          onTaxModeChanged: _onTaxModeChanged,
          onCreateOrder: _saveOrder,
          onCancel: () => Navigator.pop(context),
          isLoading: _isLoading,
          canCreate: _selectedCustomer != null && _orderItems.isNotEmpty,
        ),
      ],
    );
  }

  Widget _buildCustomerSection() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppTheme.backgroundWhite,
        border: Border.all(color: AppTheme.borderLight),
        borderRadius: BorderRadius.circular(AppTheme.radiusSmall),
      ),
      child: Row(
        children: [
          const Icon(Icons.person, size: 20, color: AppTheme.primaryBlue),
          const SizedBox(width: 12),
          SizedBox(
            width: 350,
            child: CustomerAutocomplete(
              initialCustomer: _selectedCustomer,
              onCustomerSelected: (customer) {
                setState(() => _selectedCustomer = customer);
              },
            ),
          ),
          if (_selectedCustomer != null) ...[
            const Spacer(),
            Text(_selectedCustomer!.phone, style: AppTheme.bodySmall),
          ],
        ],
      ),
    );
  }

  Widget _buildOrderDetailsSection() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppTheme.backgroundWhite,
        border: Border.all(color: AppTheme.borderLight),
        borderRadius: BorderRadius.circular(AppTheme.radiusSmall),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(
                Icons.calendar_today,
                size: 20,
                color: AppTheme.primaryBlue,
              ),
              const SizedBox(width: 8),
              Text(
                'Order Details',
                style: AppTheme.bodyMedium.copyWith(
                  fontWeight: AppTheme.fontSemibold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Expected Delivery Date',
                      style: AppTheme.bodySmall.copyWith(
                        color: AppTheme.textSecondary,
                      ),
                    ),
                    const SizedBox(height: 8),
                    InkWell(
                      onTap: _selectDeliveryDate,
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 12,
                          vertical: 10,
                        ),
                        decoration: BoxDecoration(
                          border: Border.all(color: AppTheme.borderLight),
                          borderRadius: BorderRadius.circular(
                            AppTheme.radiusSmall,
                          ),
                        ),
                        child: Row(
                          children: [
                            Text(
                              '${_expectedDeliveryDate.day.toString().padLeft(2, '0')}-${_expectedDeliveryDate.month.toString().padLeft(2, '0')}-${_expectedDeliveryDate.year}',
                              style: AppTheme.bodyMedium,
                            ),
                            const Spacer(),
                            const Icon(
                              Icons.calendar_today,
                              size: 16,
                              color: AppTheme.textSecondary,
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildItemsSection() {
    return Container(
      decoration: BoxDecoration(
        color: AppTheme.backgroundWhite,
        border: Border.all(color: AppTheme.borderLight),
        borderRadius: BorderRadius.circular(AppTheme.radiusSmall),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              children: [
                const Icon(
                  Icons.shopping_cart,
                  size: 20,
                  color: AppTheme.primaryBlue,
                ),
                const SizedBox(width: 8),
                Text(
                  'Order Items',
                  style: AppTheme.bodyMedium.copyWith(
                    fontWeight: AppTheme.fontSemibold,
                  ),
                ),
              ],
            ),
          ),
          OrderItemsTable(
            items: _orderItems,
            onItemsChanged: (items) {
              setState(() {
                _orderItems.clear();
                _orderItems.addAll(items);
              });
            },
            isTaxInclusive: _isTaxInclusive,
          ),
        ],
      ),
    );
  }

  Widget _buildNotesSection() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppTheme.backgroundWhite,
        border: Border.all(color: AppTheme.borderLight),
        borderRadius: BorderRadius.circular(AppTheme.radiusSmall),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(
                Icons.note_outlined,
                size: 20,
                color: AppTheme.primaryBlue,
              ),
              const SizedBox(width: 8),
              Text(
                'Notes',
                style: AppTheme.bodyMedium.copyWith(
                  fontWeight: AppTheme.fontSemibold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          TextField(
            controller: _orderSummaryController,
            style: AppTheme.bodyMedium,
            maxLines: 3,
            decoration: const InputDecoration(
              labelText: 'Order Summary',
              hintText: 'Enter order summary...',
              alignLabelWithHint: true,
            ),
          ),
          const SizedBox(height: 16),
          TextField(
            controller: _customerInstructionsController,
            style: AppTheme.bodyMedium,
            maxLines: 3,
            decoration: const InputDecoration(
              labelText: 'Customer Instructions',
              hintText: 'Enter customer instructions...',
              alignLabelWithHint: true,
            ),
          ),
        ],
      ),
    );
  }
}
